# Hacks needed to get 3.7 working with Travis-CI at present
dist: xenial
sudo: yes

language: python

python:
  - "3.7"

addons:
  sonarcloud:
    organization: "chidgey-github"

script:
  - python ./projects/blackjack/tests/test_blackjackgame.py
  - sonar-scanner

# python -m unittest discover -s ./projects/blackjack/tests --verbose
# Review: https://docs.travis-ci.com/user/deployment/pypi/